version: "3"
services:
  siglens:
    user: 0:0
    restart: always
    image: elestio/siglens:${SOFTWARE_VERSION_TAG}
    ports:
      - "172.17.0.1:42011:8081"
      - "172.17.0.1:23383:5122"
    volumes:
      - "./storage/data:/siglens/data"
      - "./storage/logs:/siglens/logs"
      - "./storage/server.yaml:/siglens/server.yaml"
      - /root/.acme.sh/vm.elestio.app/fullchain.cer:/etc/fullchain.cer
      - /root/.acme.sh/vm.elestio.app/vm.elestio.app.key:/etc/vm.elestio.app.key
    command: ["./siglens", "--config", "server.yaml"]
